site_name: Yegge Docs
site_url: https://docs.yegge.com

theme:
  name: material
  logo: _assets/logo.svg
  features: navigation.indexes
  # font…
  palette:
    - scheme: slate
      primary: indigo    # ← was black; switch to indigo (or remove this line)
      accent: indigo

extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - About: about.md
  - A.I. Prompts: ai-prompts/index.md
  - Contact: contact.md
  
plugins:
  - search